In [228]:
import numpy as np
import pandas as pd

In [229]:
#%pip install kagglehub

In [230]:
#import kagglehub
#path = kagglehub.dataset_download("rayyanfaridy/myanimelist-anime-dataset")
#print("Path to dataset files:", path)

In [231]:
import os
import pandas as pd
directory_path = "/kaggle/input/myanimelist-anime-dataset"
file_name = os.listdir(directory_path)[0]
file_path = os.path.join(directory_path, file_name)
anime_df = pd.read_csv(file_path)
print(f"DataFrame 'anime_df' loaded successfully from {file_name}.")

DataFrame 'anime_df' loaded successfully from anime_full_dataset.csv.

In [232]:
anime_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28822 entries, 0 to 28821
Data columns (total 24 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   anime_id         28821 non-null  object
 1   title            28821 non-null  object
 2   english_title    12595 non-null  object
 3   japanese_title   28653 non-null  object
 4   synopsis         23798 non-null  object
 5   type             28747 non-null  object
 6   source           28820 non-null  object
 7   episodes         28061 non-null  float64
 8   status           28822 non-null  object
 9   duration         28821 non-null  object
 10  rating           28207 non-null  object
 11  year             6104 non-null   float64
 12  season           6104 non-null   object
 13  score            18591 non-null  object
 14  scored_by        18591 non-null  object
 15  members          28821 non-null  object
 16  favorites        28821 non-null  object
 17  rank             21736 non-null  object
 18  popularity       28820 non-null  float64
 19  genres           28821 non-null  object
 20  explicit_genres  28821 non-null  object
 21  themes           28821 non-null  object
 22  demographics     28821 non-null  object
 23  studios          28821 non-null  object
dtypes: float64(3), object(21)
memory usage: 5.3+ MB

In [233]:
anime_df.describe()

           episodes         year    popularity
count  28061.000000  6104.000000  28820.000000
mean      13.975648  2010.377785  14847.128557
std       47.140421    14.841722   8670.521682
min        1.000000  1495.000000      0.000000
25%        1.000000  2005.000000   7350.000000
50%        2.000000  2014.000000  14906.500000
75%       13.000000  2020.000000  22406.250000
max     3000.000000  2027.000000  29696.000000

In [234]:
anime_df['rating'].value_counts()

rating
PG-13 - Teens 13 or older         10625
G - All Ages                       8990
PG - Children                      4371
Rx - Hentai                        1537
R - 17+ (violence & profanity)     1528
R+ - Mild Nudity                   1155
48                                    1
Name: count, dtype: int64

In [235]:
anime_df['type'].value_counts()

type
TV                      8248
Movie                   4794
Music                   4252
ONA                     4205
OVA                     4007
Special                 1649
TV Special               753
CM                       511
PV                       327
BadResponseException       1
Name: count, dtype: int64

In [236]:
anime_df[anime_df['type']=='BadResponseException']

,anime_id,title,english_title,japanese_title,synopsis,type,source,episodes,status,duration,...,scored_by,members,favorites,rank,popularity,genres,explicit_genres,themes,demographics,studios
6260,NaN,NaN,NaN,NaN,NaN,BadResponseException,NaN,NaN,404,NaN,...,NaN,NaN,NaN,NaN,NaN,[],[],[],[],[]

In [237]:
anime_df['status'].value_counts()

status
Finished Airing     27857
Not yet aired         584
Currently Airing      379
404                     1
2195.0                  1
Name: count, dtype: int64

In [238]:
anime_df[(anime_df['status']=='404') | (anime_df['status']=='2195.0')]

,anime_id,title,english_title,japanese_title,synopsis,type,source,episodes,status,duration,...,scored_by,members,favorites,rank,popularity,genres,explicit_genres,themes,demographics,studios
6260,NaN,NaN,NaN,NaN,NaN,BadResponseException,NaN,NaN,404,NaN,...,NaN,NaN,NaN,NaN,NaN,[],[],[],[],[]
25022,"novel""",16.0,Finished Airing,19 min per ep,PG-13 - Teens 13 or older,NaN,NaN,7.66,2195.0,7415,...,[],[],[],"[""Foch Film""]",NaN,NaN,NaN,NaN,NaN,NaN

In [239]:
anime_df['rating'].value_counts()

rating
PG-13 - Teens 13 or older         10625
G - All Ages                       8990
PG - Children                      4371
Rx - Hentai                        1537
R - 17+ (violence & profanity)     1528
R+ - Mild Nudity                   1155
48                                    1
Name: count, dtype: int64

In [240]:
anime_df[anime_df['rating']=='48']

,anime_id,title,english_title,japanese_title,synopsis,type,source,episodes,status,duration,...,scored_by,members,favorites,rank,popularity,genres,explicit_genres,themes,demographics,studios
25022,"novel""",16.0,Finished Airing,19 min per ep,PG-13 - Teens 13 or older,NaN,NaN,7.66,2195.0,7415,...,[],[],[],"[""Foch Film""]",NaN,NaN,NaN,NaN,NaN,NaN

In [241]:
bad_rows = anime_df[(anime_df['status'] == '404') | (anime_df['status'] == '2195.0')].index
anime_df = anime_df.drop(bad_rows).reset_index(drop=True)

In [242]:
anime_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28820 entries, 0 to 28819
Data columns (total 24 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   anime_id         28820 non-null  object
 1   title            28820 non-null  object
 2   english_title    12594 non-null  object
 3   japanese_title   28652 non-null  object
 4   synopsis         23797 non-null  object
 5   type             28746 non-null  object
 6   source           28820 non-null  object
 7   episodes         28060 non-null  float64
 8   status           28820 non-null  object
 9   duration         28820 non-null  object
 10  rating           28206 non-null  object
 11  year             6103 non-null   float64
 12  season           6103 non-null   object
 13  score            18590 non-null  object
 14  scored_by        18590 non-null  object
 15  members          28820 non-null  object
 16  favorites        28820 non-null  object
 17  rank             21735 non-null  object
 18  popularity       28820 non-null  float64
 19  genres           28820 non-null  object
 20  explicit_genres  28820 non-null  object
 21  themes           28820 non-null  object
 22  demographics     28820 non-null  object
 23  studios          28820 non-null  object
dtypes: float64(3), object(21)
memory usage: 5.3+ MB

In [243]:
anime_df['score'] = pd.to_numeric(anime_df['score'], errors='coerce')
anime_df['scored_by'] = pd.to_numeric(anime_df['scored_by'], errors='coerce')
anime_df['members'] = pd.to_numeric(anime_df['members'], errors='coerce')
anime_df['favorites'] = pd.to_numeric(anime_df['favorites'], errors='coerce')
anime_df['rank'] = pd.to_numeric(anime_df['rank'], errors='coerce')
anime_df['anime_id'] = pd.to_numeric(anime_df['anime_id'], errors='coerce')

In [244]:
columns=anime_df.columns
columns

Index(['anime_id', 'title', 'english_title', 'japanese_title', 'synopsis',
       'type', 'source', 'episodes', 'status', 'duration', 'rating', 'year',
       'season', 'score', 'scored_by', 'members', 'favorites', 'rank',
       'popularity', 'genres', 'explicit_genres', 'themes', 'demographics',
       'studios'],
      dtype='object')

In [245]:
def printnas(df):
  for i in columns:
    print(df[i].isna().value_counts());

In [246]:
printnas(anime_df)

anime_id
False    28820
Name: count, dtype: int64
title
False    28820
Name: count, dtype: int64
english_title
True     16226
False    12594
Name: count, dtype: int64
japanese_title
False    28652
True       168
Name: count, dtype: int64
synopsis
False    23797
True      5023
Name: count, dtype: int64
type
False    28746
True        74
Name: count, dtype: int64
source
False    28820
Name: count, dtype: int64
episodes
False    28060
True       760
Name: count, dtype: int64
status
False    28820
Name: count, dtype: int64
duration
False    28820
Name: count, dtype: int64
rating
False    28206
True       614
Name: count, dtype: int64
year
True     22717
False     6103
Name: count, dtype: int64
season
True     22717
False     6103
Name: count, dtype: int64
score
False    18590
True     10230
Name: count, dtype: int64
scored_by
False    18590
True     10230
Name: count, dtype: int64
members
False    28820
Name: count, dtype: int64
favorites
False    28820
Name: count, dtype: int64
rank
False    21735
True      7085
Name: count, dtype: int64
popularity
False    28820
Name: count, dtype: int64
genres
False    28820
Name: count, dtype: int64
explicit_genres
False    28820
Name: count, dtype: int64
themes
False    28820
Name: count, dtype: int64
demographics
False    28820
Name: count, dtype: int64
studios
False    28820
Name: count, dtype: int64

In [247]:
anime_df = anime_df.dropna(subset=['synopsis'])

In [248]:
anime_df = anime_df.dropna(subset=['type'])

In [249]:
anime_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 23732 entries, 0 to 28819
Data columns (total 24 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   anime_id         23732 non-null  float64
 1   title            23732 non-null  object
 2   english_title    11513 non-null  object
 3   japanese_title   23590 non-null  object
 4   synopsis         23732 non-null  object
 5   type             23732 non-null  object
 6   source           23732 non-null  object
 7   episodes         23146 non-null  float64
 8   status           23732 non-null  object
 9   duration         23732 non-null  object
 10  rating           23274 non-null  object
 11  year             5615 non-null   float64
 12  season           5615 non-null   object
 13  score            17998 non-null  float64
 14  scored_by        17998 non-null  float64
 15  members          23732 non-null  float64
 16  favorites        23732 non-null  float64
 17  rank             17107 non-null  float64
 18  popularity       23732 non-null  float64
 19  genres           23732 non-null  object
 20  explicit_genres  23732 non-null  object
 21  themes           23732 non-null  object
 22  demographics     23732 non-null  object
 23  studios          23732 non-null  object
dtypes: float64(9), object(15)
memory usage: 4.5+ MB

In [250]:
printnas(anime_df)

anime_id
False    23732
Name: count, dtype: int64
title
False    23732
Name: count, dtype: int64
english_title
True     12219
False    11513
Name: count, dtype: int64
japanese_title
False    23590
True       142
Name: count, dtype: int64
synopsis
False    23732
Name: count, dtype: int64
type
False    23732
Name: count, dtype: int64
source
False    23732
Name: count, dtype: int64
episodes
False    23146
True       586
Name: count, dtype: int64
status
False    23732
Name: count, dtype: int64
duration
False    23732
Name: count, dtype: int64
rating
False    23274
True       458
Name: count, dtype: int64
year
True     18117
False     5615
Name: count, dtype: int64
season
True     18117
False     5615
Name: count, dtype: int64
score
False    17998
True      5734
Name: count, dtype: int64
scored_by
False    17998
True      5734
Name: count, dtype: int64
members
False    23732
Name: count, dtype: int64
favorites
False    23732
Name: count, dtype: int64
rank
False    17107
True      6625
Name: count, dtype: int64
popularity
False    23732
Name: count, dtype: int64
genres
False    23732
Name: count, dtype: int64
explicit_genres
False    23732
Name: count, dtype: int64
themes
False    23732
Name: count, dtype: int64
demographics
False    23732
Name: count, dtype: int64
studios
False    23732
Name: count, dtype: int64

In [251]:
import json
json_cols = ['genres','explicit_genres','themes', 'demographics', 'studios']

In [252]:
def json_counts(anime_df):
  for i in json_cols:
    print(anime_df[i].value_counts())

In [253]:
json_counts(anime_df)

genres
[]                                                                 4524
["Comedy"]                                                         2394
["Hentai"]                                                         1053
["Slice of Life"]                                                   819
["Fantasy"]                                                         758
                                                                   ...
["Fantasy", "Horror", "Sci-Fi", "Suspense"]                           1
["Fantasy", "Gourmet", "Romance"]                                     1
["Avant Garde", "Drama", "Sci-Fi", "Suspense"]                        1
["Avant Garde", "Award Winning", "Drama", "Sci-Fi", "Suspense"]       1
["Avant Garde", "Drama", "Mystery", "Sci-Fi", "Suspense"]             1
Name: count, Length: 841, dtype: int64
explicit_genres
[]    23732
Name: count, dtype: int64
themes
[]                                                      8330
["Music"]                                               4060
["School"]                                               831
["Historical"]                                           684
["Mecha"]                                                501
                                                        ...
["Crossdressing", "Historical", "Mecha", "Military"]       1
["Detective", "Reincarnation"]                             1
["Anthropomorphic", "Educational", "Music"]                1
["Childcare", "Isekai", "Reincarnation"]                   1
["Anthropomorphic", "Music", "Super Power"]                1
Name: count, Length: 1010, dtype: int64
demographics
[]                       16544
["Kids"]                  3438
["Shounen"]               1995
["Seinen"]                1072
["Shoujo"]                 480
["Josei"]                  156
["Kids", "Shounen"]         44
["Kids", "Shoujo"]           1
["Seinen", "Shounen"]        1
["Shoujo", "Shounen"]        1
Name: count, dtype: int64
studios
[]                                                                           7899
["Toei Animation"]                                                            801
["Sunrise"]                                                                   510
["J.C.Staff"]                                                                 392
["TMS Entertainment"]                                                         321
                                                                             ...
["Tiao Tiao Tang Donghua"]                                                      1
["Number 19 Animation"]                                                         1
["Shou Fan Yu Shu Gongzuoshi", "InfiniOrange Animation Studio", "Origin"]       1
["Liliyabi Company Introduction"]                                               1
["Lychee Time Media"]                                                           1
Name: count, Length: 1903, dtype: int64

In [254]:
anime_df['explicit_genres'].value_counts()

explicit_genres
[]    23732
Name: count, dtype: int64

In [255]:
for col in json_cols:
    anime_df[col] = anime_df[col].apply(lambda x: json.loads(x) if pd.notna(x) else [])

In [256]:
anime_df = anime_df.drop(columns=['explicit_genres'])

In [257]:
json_cols.remove('explicit_genres')

In [258]:
json_counts(anime_df)

genres
[]                                                       4524
[Comedy]                                                 2394
[Hentai]                                                 1053
[Slice of Life]                                           819
[Fantasy]                                                 758
                                                         ...
[Fantasy, Horror, Sci-Fi, Suspense]                         1
[Fantasy, Gourmet, Romance]                                 1
[Avant Garde, Drama, Sci-Fi, Suspense]                      1
[Avant Garde, Award Winning, Drama, Sci-Fi, Suspense]       1
[Avant Garde, Drama, Mystery, Sci-Fi, Suspense]             1
Name: count, Length: 841, dtype: int64
themes
[]                                              8330
[Music]                                         4060
[School]                                         831
[Historical]                                     684
[Mecha]                                          501
                                                ...
[Crossdressing, Historical, Mecha, Military]       1
[Detective, Reincarnation]                         1
[Anthropomorphic, Educational, Music]              1
[Childcare, Isekai, Reincarnation]                 1
[Anthropomorphic, Music, Super Power]              1
Name: count, Length: 1010, dtype: int64
demographics
[]                   16544
[Kids]                3438
[Shounen]             1995
[Seinen]              1072
[Shoujo]               480
[Josei]                156
[Kids, Shounen]         44
[Kids, Shoujo]           1
[Seinen, Shounen]        1
[Shoujo, Shounen]        1
Name: count, dtype: int64
studios
[]                                                                     7899
[Toei Animation]                                                        801
[Sunrise]                                                               510
[J.C.Staff]                                                             392
[TMS Entertainment]                                                     321
                                                                       ...
[Tiao Tiao Tang Donghua]                                                  1
[Number 19 Animation]                                                     1
[Shou Fan Yu Shu Gongzuoshi, InfiniOrange Animation Studio, Origin]       1
[Liliyabi Company Introduction]                                           1
[Lychee Time Media]                                                       1
Name: count, Length: 1903, dtype: int64

In [259]:
anime_df['synopsis'].value_counts()

synopsis
No synopsis has been added for this series yet.\n\nClick here to update this information.    22
Film by Takashi Ito.                                                                         12
Furukawa Taku film.                                                                          11
A short animation by Taku Furukawa.                                                           9
A short film by Okamoto Tadanari.                                                             7
                                                                                             ..
Bad Badtz-Maru and friends re-create the classic story of The Boy Who Cried Wolf.             1
Kitty and friends recreate the story of Puss in Boots.                                        1
Kitty and friends re-create the story of Momotarou.                                           1
Part 1 Hello Kitty version of Heidi, a novel by Johanna Spyri.                                1
Animated music video of Purin-chan (Abe Natsumi)'s Pi~hyara Kouta.                            1
Name: count, Length: 23458, dtype: int64

In [260]:
placeholder = "No synopsis has been added for this series yet."
anime_df = anime_df[~anime_df['synopsis'].str.contains(placeholder, na=False)].reset_index(drop=True)

anime_df = anime_df[anime_df['synopsis'].str.len() > 100].reset_index(drop=True)

In [261]:
anime_df.shape

(16955, 23)

In [262]:
anime_df['type'].value_counts()

type
TV            5233
OVA           3034
Movie         2864
ONA           2315
Music         1768
Special        848
TV Special     444
CM             288
PV             161
Name: count, dtype: int64

In [263]:
anime_df['rating'].value_counts()

rating
PG-13 - Teens 13 or older         7171
G - All Ages                      4994
R - 17+ (violence & profanity)    1232
PG - Children                     1161
Rx - Hentai                       1126
R+ - Mild Nudity                   921
Name: count, dtype: int64

In [264]:
anime_df = anime_df[~anime_df['type'].isin(['Music', 'CM', 'PV'])].reset_index(drop=True)
anime_df = anime_df[anime_df['rating'] != 'Rx - Hentai'].reset_index(drop=True)
anime_df.shape

(13612, 23)

In [266]:
json_counts(anime_df)

genres
[Comedy]                                           1401
[]                                                  896
[Action, Adventure, Fantasy]                        517
[Drama]                                             503
[Slice of Life]                                     465
                                                   ...
[Adventure, Fantasy, Suspense]                        1
[Drama, Gourmet, Mystery]                             1
[Action, Adventure, Comedy, Fantasy, Gourmet]         1
[Action, Comedy, Drama, Romance, Supernatural]        1
[Action, Comedy, Horror, Mystery, Supernatural]       1
Name: count, Length: 759, dtype: int64
themes
[]                                           5051
[School]                                      610
[Historical]                                  479
[Mecha]                                       403
[Music]                                       271
                                             ...
[CGDCT, Educational]                            1
[Detective, Gag Humor]                          1
[Historical, Parody, School, Super Power]       1
[Harem, School, Showbiz]                        1
[Gag Humor, Mahou Shoujo]                       1
Name: count, Length: 939, dtype: int64
demographics
[]                   8864
[Kids]               1645
[Shounen]            1636
[Seinen]              890
[Shoujo]              409
[Josei]               123
[Kids, Shounen]        42
[Kids, Shoujo]          1
[Seinen, Shounen]       1
[Shoujo, Shounen]       1
Name: count, dtype: int64
studios
[]                                                                     2649
[Toei Animation]                                                        655
[Sunrise]                                                               402
[J.C.Staff]                                                             328
[Madhouse]                                                              274
                                                                       ...
[Gainax, Tatsunoko Production]                                            1
[Lychee Time Media]                                                       1
[Liliyabi Company Introduction]                                           1
[Shou Fan Yu Shu Gongzuoshi, InfiniOrange Animation Studio, Origin]       1
[Number 19 Animation]                                                     1
Name: count, Length: 1499, dtype: int64

In [267]:
anime_df['tags'] = anime_df['genres'] + anime_df['themes'] + anime_df['demographics']
anime_df['tags'] = anime_df['tags'].apply(lambda x: ' '.join(x))

In [270]:
anime_df['text_for_embedding'] = anime_df['synopsis'] + ' ' + anime_df['tags']

In [272]:
anime_df.head()

,anime_id,title,english_title,japanese_title,synopsis,type,source,episodes,status,duration,...,members,favorites,rank,popularity,genres,themes,demographics,studios,tags,text_for_embedding
0,1.0,Cowboy Bebop,Cowboy Bebop,カウボーイビバップ,"Crime is timeless. By the year 2071, humanity ...",TV,Original,26.0,Finished Airing,24 min per ep,...,2033582.0,88901.0,47.0,42.0,"[Action, Award Winning, Sci-Fi]","[Adult Cast, Space]",[],[Sunrise],Action Award Winning Sci-Fi Adult Cast Space,"Crime is timeless. By the year 2071, humanity ..."
1,6.0,Trigun,Trigun,トライガン,"Vash the Stampede is the man with a $$60,000,0...",TV,Manga,26.0,Finished Airing,24 min per ep,...,825583.0,17438.0,408.0,265.0,"[Action, Adventure, Sci-Fi]",[Adult Cast],[Shounen],[Madhouse],Action Adventure Sci-Fi Adult Cast Shounen,"Vash the Stampede is the man with a $$60,000,0..."
2,7.0,Witch Hunter Robin,Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),"Though hidden away from the general public, Wi...",TV,Original,26.0,Finished Airing,25 min per ep,...,127702.0,694.0,3418.0,1984.0,"[Action, Drama, Mystery, Supernatural]",[Detective],[],[Sunrise],Action Drama Mystery Supernatural Detective,"Though hidden away from the general public, Wi..."
3,8.0,Bouken Ou Beet,Beet the Vandel Buster,冒険王ビィト,It is the dark century and the people are suff...,TV,Manga,52.0,Finished Airing,23 min per ep,...,16589.0,18.0,4909.0,5843.0,"[Action, Adventure, Fantasy]",[],[Shounen],[Toei Animation],Action Adventure Fantasy Shounen,It is the dark century and the people are suff...
4,15.0,Eyeshield 21,NaN,アイシールド21,"Shy, reserved, and small-statured, Deimon High...",TV,Manga,145.0,Finished Airing,23 min per ep,...,194861.0,2108.0,862.0,1406.0,[Sports],[Team Sports],[Shounen],[Gallop],Sports Team Sports Shounen,"Shy, reserved, and small-statured, Deimon High..."

In [271]:
anime_df.to_csv('anime_clean.csv', index=False)